print("Program starting.")
print("Estimate how many minutes you spent on programming... \n")
t1 = input("A1_T1: ")
t2 = input("A1_T2: ")
t3 = input("A1_T3: ")
t4 = input("A1_T4: ")
t5 = input("A1_T5: ")
t6 = input("A1_T6: ")
t7 = input("A1_T7: ")
sum = int(t1) + int(t2) + int(t3) + int(t4) + int(t5) + int(t6) + int(t7)
print(f"\nIn total you spent {sum} minutes on programming.")
average = (sum) / 7
rounded = round(average)
print(f"Average per task was {average:.2f} min and same rounded to the nearest integer {rounded} min")
print("\nProgram ending.")
