print("Program starting.")
name = input("What is your name: ")
num1 = input("Enter a floating point number: ")
num2 = input("Enter second floating point number: ")
print(f"{name} you gave numbers {num1} and {num2}")
mul = (float(num1) * float(num2))
rounded = round(mul, 2)
print(f"Multiplying first and second number will result in product {rounded}")
print("Program ending.")
